export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

export const GET_CATS = 'GET_CATS';
export const GET_CATS_WITH_CATEGORY_ID = 'GET_CATS_WITH_CATEGORY_ID';
export const GET_MORE_CATS_WITH_CATEGORY_ID = 'GET_MORE_CATS_WITH_CATEGORY_ID';
export const CATS_ERROR = 'CATS_ERROR';